### PR TITLE
feat(expose editor object): defineExpose editor

### PR DESCRIPTION
**Pull request by kissmannchristoph**
this change is because i need the `getText` and other functions from the editor
or do you know another solution?

### CODE REVIEW

**Comment by yikoyu** [comment]
What do you think of this?
https://github.com/yikoyu/vuetify-pro-tiptap/blob/153fdedf59805bcd6ce43f2b05f2ee223f608ee6/src/components/VuetifyTiptap.vue#L22

[feat-output](https://github.com/yikoyu/vuetify-pro-tiptap/commit/153fdedf59805bcd6ce43f2b05f2ee223f608ee6)

**Comment by kissmannchristoph** [comment]
@yikoyu i need html and text,
text for diff
and html as content

**Comment by yikoyu** [comment]
https://github.com/yikoyu/vuetify-pro-tiptap/blob/2c069cdc2fd6699ef1fc259507f47cf67fe35860/src/components/VuetifyTiptap.vue#L98

[add emit change ](https://github.com/yikoyu/vuetify-pro-tiptap/commit/2c069cdc2fd6699ef1fc259507f47cf67fe35860)

**Comment by kissmannchristoph** [comment]
if i define this with @change="(editor) => console.log('editor, editor)" nothing happend

image

**Comment by yikoyu** [comment]
https://github.com/yikoyu/vuetify-pro-tiptap/pull/184

**Pull request closed without merging**
